#include "../header/io.h"
#include "../header/rand.h"

static char input[10];          /* input for store /dev/urandom */
static int RANDOM_INPUT = 10;   /* number of randoms generated by each /dev/urandom call */

/*
    Generate random number by reading /dev/urandom
*/
int _rand(){
    /*
        make a buffer and store 9 random bytes(generated by /dev/urandom) in buffer.
        call /dev/urandom every 8 _rand() call.
        use one byte in buffer per each _rand() call.
    */
    if(RANDOM_INPUT > 8){
        unsigned int f = myfopen("/dev/urandom", 'r');
        mynfread(f, input, 9);
        myfclose(f);
        RANDOM_INPUT = 0;
    }
    int random = UINT(input[RANDOM_INPUT]);

    /* Seed Would be used HERE */
    random = ((random * 1000) - random) & SEED;

    /* make sure a random number is big enough */
    while (random < (RMAX / 10)){
        random *= random;
    }
    ++RANDOM_INPUT;
    return random;
}
